const grupos: string[] = [
  "Los Van Van",
  "NG La Banda",
  "Issac Delgado",
  "Paulo FG",
  "Bamboleo",
  "Maykel Blanco y su Salsa Mayor",
  "Manolito y su Trabuco",
  "Adalberto Alvarez y su Son",
  "Pupy y Los Que Son Son",
  "Alexander Abreu y Havana D'Primera",
  "Elito Reve y su Charangon",
  "Habana D'Primera",
  "Charanga Habanera",
  "Azucar Negra",
  "Havana C",
  "La Colmenita",
  "Barbaro Fines y su Mayimbe",
  "Giraldo Piloto y Klimax",
  "David Calzado y su Charanga Habanera",
  "Anacaona",
  "La Elite",
  "Los 4",
  "Maraca",
  "Dan Den",
  "Qva Libre",
  "Timbalive",
  "Manana Club",
  "La Charanga Forever",
  "Los Conquistadores de la Salsa",
  "NG2",
  "Cubanismo",
  "NG La Banda - Oro",
  "Leonel Limonta y Azucar Negra",
  "Los Taínos de Mayari",
  "Timba Talmud",
  "Timba Live Band",
  "Soneros de Verdad",
  "Son 14",
  "La Mecanica Loca",
  "Yumuri y sus Hermanos",
  "Caribe Girls",
  "Juana Bacallao",
  "Doble Impacto",
  "La Mulata del Sabor",
  "Yoruba Andabo",
  "El Nino y la Verdad",
  "Conjunto Cespedes",
  "Yasser Ramos y su Orquesta",
  "Haila Mompie",
  "El Chacal y Yakarta",
  "Tumbao Habana",
  "La Sucursal SA",
  "Aroma y Sabor",
  "Orquesta Aragon",
  "Septeto Santiaguero",
  "Cuba Libre",
  "Issac Delgado y su Grupo",
  "Pachito Alonso y sus Kini Kini",
  "Estrellas de Areito",
  "Los Reyes 73",
  "Adonis y Osain del Monte",
  "Grupo Niche",
  "Orquesta Revé",
  "Mangu",
  "Tania Pantoja",
  "Los Jubilados",
  "Arlenys Rodriguez",
  "El Yonki",
  "El Noro y Primera Clase",
  "La Ritmo Oriental",
  "Grupo Galé",
  "Tobaco y Ron",
  "El Trabuco Venezolano",
  "Los Van Van - Songo",
  "La Conga de Los Hoyos",
  "Maravilla de Florida",
  "Changui de Guantanamo",
  "Son del Barrio",
  "Salsa Mayor",
  "La Moderna Tradición",
  "Oscar de Leon",
  "Tirso Duarte",
  "Eduardo Morales",
  "Homenaje a Benny More",
  "Grupo America",
  "Pachito Alonso y sus Kini Kini - Oro",
  "Orquesta Failde",
  "Haila Maria Mompie",
  "Puro Habano",
  "Sonido Contemporáneo",
  "Axel Tosca"
];
